#!/bin/bash

baseDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
libdir="$baseDir/usr/lib"
MainApp="$baseDir/usr/bin/DailyDesktopWallpaperPlus"

ulimit -c unlimited
chmod u+x $MainApp
export LD_LIBRARY_PATH=$libdir
exec $MainApp