name: dailydesktopwallpaperplus
version: "1.0"
summary: Set the daily photo of Bing or of Windows Spotlight as your wallpaper
description: |
  This Application is a variant which you can automatically set the daily photo of Bing or of Windows Spotlight as your Wallpaper on your Linux machine.
confinement: strict
grade: stable
icon: icon/mainicon.png
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  dailydesktopwallpaperplus:
    command: DailyDesktopWallpaperPlus
    plugs:
        - home
        - network
        - opengl
        - x11
        - desktop
        - network-manager
        - desktop-legacy

parts:
  dailydesktopwallpaperplus:
     source-type: git
     source: https://github.com/pgc062020/DailyDesktopWallpaperPlus.git 
     plugin: qmake
     qt-version: qt5
     build-packages:
       - build-essential
       - qtbase5-dev
       - dpkg-dev
     stage-packages:
       - libqt5gui5
